[package]
name = "amd-host-image-builder"
version = "0.1.0"
edition = "2018"
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amd-apcb = { git = "ssh://git@github.com/oxidecomputer/amd-apcb.git", rev = "6d12c1f16f5b9cfb13dee574fa80a5b79babb8b9", features = [] }
amd-efs = { git = "ssh://git@github.com/oxidecomputer/amd-efs.git", rev = "68037041ace74da9519593c1cdeb9e17457c2199", features = ["std"] }
amd-flash = { git = "ssh://git@github.com/oxidecomputer/amd-flash.git", branch = "main" }
goblin = { version = "0.4", features = ["elf64", "endian_fd"] }
#serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.3"
amd-host-image-builder-config = { path = "amd-host-image-builder-config" }

[build-dependencies]
amd-apcb = { git = "ssh://git@github.com/oxidecomputer/amd-apcb.git", rev = "6d12c1f16f5b9cfb13dee574fa80a5b79babb8b9", features = [] }
amd-efs = { git = "ssh://git@github.com/oxidecomputer/amd-efs.git", rev = "68037041ace74da9519593c1cdeb9e17457c2199", features = ["std"] }
amd-host-image-builder-config = { path = "amd-host-image-builder-config" }
schemars = "0.8.8"
serde_json = "1.0.78"
