[package]
name = "amd-host-image-builder"
version = "0.1.0"
edition = "2018"
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amd-apcb = { git = "ssh://git@github.com/oxidecomputer/amd-apcb.git", rev = "41cca4e6bfaa6f1d5f319a9cdceceab1d0bb27ce", features = ["serde", "schemars"] }
amd-efs = { git = "ssh://git@github.com/oxidecomputer/amd-efs.git", rev = "0a13a3988a32deb974aa2ddfeb7b069b43a6727a", features = ["std"] }
amd-flash = { git = "ssh://git@github.com/oxidecomputer/amd-flash.git", branch = "main" }
goblin = { version = "0.4", features = ["elf64", "endian_fd"] }
#serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.78"
structopt = "0.3"
amd-host-image-builder-config = { path = "amd-host-image-builder-config" }

[build-dependencies]
amd-apcb = { git = "ssh://git@github.com/oxidecomputer/amd-apcb.git", rev = "41cca4e6bfaa6f1d5f319a9cdceceab1d0bb27ce", features = ["serde", "schemars"] }
amd-efs = { git = "ssh://git@github.com/oxidecomputer/amd-efs.git", rev = "0a13a3988a32deb974aa2ddfeb7b069b43a6727a", features = ["std"] }
amd-host-image-builder-config = { path = "amd-host-image-builder-config" }
schemars = "0.8.8"
serde_json = "1.0.78"
valico = "2"
