[package]
name = "amd-host-image-builder-config"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amd-apcb = { git = "ssh://git@github.com/oxidecomputer/amd-apcb.git", branch = "main", features = ["std"] }
amd-efs = { git = "ssh://git@github.com/oxidecomputer/amd-efs.git", rev = "5af452c9b6c84cffbdc60c5aa015c60a07e4e7db", features = ["std"] }
amd-flash = { git = "ssh://git@github.com/oxidecomputer/amd-flash.git", branch = "main" }
schemars = "0.8.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
