#
# This file, with this flag, must be present in the default branch in order for
# the buildomat integration to create check suites.
#
enable = true

#
# This repository needs access to several other private repositories:
#
access_repos = [
	"oxidecomputer/amd-apcb",
	"oxidecomputer/amd-efs",
	"oxidecomputer/amd-flash",
	"oxidecomputer/nanobl-rs",
]

#
# Require approval for pull requests made by users outside our organisation.
#
org_only = true
